// Generated by extract_ports.py for ports_tnx5.i

#ifndef PORTS_TNX5_H
#define PORTS_TNX5_H

#define NPORTB 0x18
#define NDDRB 0x17
#define NPINB 0x16
#define NTCNT0 0x32
#define NTCNT1 0x2F
#define NOCR0A 0x29
#define NOCR0B 0x28
#define NOCR1A 0x2E
#define NOCR1B 0x2B
#define NTIMSK 0x39
#define NTIFR 0x38
#define NTCCR0A 0x2A
#define NTCCR0B 0x33
#define NGTCCR 0x2C
#define NGIFR 0x3A
#define NPCMSK 0x15

#endif // PORTS_TNX5_H
