// Generated by extract_ports.py for ports_mx8.i

#ifndef PORTS_MX8_H
#define PORTS_MX8_H

#define NPORTB 0x05
#define NDDRB 0x04
#define NPINB 0x03
#define NPORTC 0x08
#define NDDRC 0x07
#define NPINC 0x06
#define NPORTD 0x0B
#define NDDRD 0x0A
#define NPIND 0x09
#define NPCICR 0x48
#define NPCIFR 0x1B
#define NPCMSK0 0x4B
#define NPCMSK1 0x4C
#define NPCMSK2 0x4D
#define NSPCR 0x2C
#define NEICRA 0x49
#define NEIMSK 0x1D
#define NICR1 0x66
#define NTCNT0 0x26
#define NTCNT1 0x64
#define NTCNT2 0x92
#define NOCR0A 0x27
#define NOCR0B 0x28
#define NOCR1A 0x68
#define NOCR1B 0x6A
#define NOCR2A 0x93
#define NOCR2B 0x94
#define NTIMSK0 0x4E
#define NTIMSK1 0x4F
#define NTIMSK2 0x50
#define NTIFR0 0x15
#define NTIFR1 0x16
#define NTIFR2 0x17
#define NTCCR0A 0x24
#define NTCCR0B 0x25
#define NTCCR1A 0x60
#define NTCCR1B 0x61
#define NTCCR1C 0x62
#define NTCCR2A 0x90
#define NTCCR2B 0x91
#define NUBRR0H 0xA5
#define NUBRR0L 0xA4
#define NUCSR0A 0xA0
#define NUCSR0B 0xA1
#define NUDR0 0xA6

#endif // PORTS_MX8_H
